# Generated by Django 2.2.1 on 2019-05-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postitapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='post',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postitapp.CommentModel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='body',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='body',
            field=models.TextField(max_length=3000),
        ),
    ]
