# Generated by Django 2.2.1 on 2019-05-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postitapp', '0004_auto_20190517_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='comments',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='comments',
            field=models.ManyToManyField(to='postitapp.CommentModel'),
        ),
    ]
