# Generated by Django 2.2.1 on 2019-05-18 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postitapp', '0005_auto_20190517_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='body',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='body',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(3000)]),
        ),
    ]
