# Generated by Django 2.2.1 on 2019-05-30 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postitapp', '0006_auto_20190518_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftModel',
            fields=[
                ('postmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='postitapp.PostModel')),
            ],
            bases=('postitapp.postmodel',),
        ),
    ]
